### PR TITLE
Create svx-1.2.2.md

### PR DESCRIPTION
**Pull request by anastasiaUsik**

### CODE REVIEW

**Comment by YVLopez** [comment]
@anastasiaUsik, great work! I've done a grammatical review, but I'm not sure about line 46 - could you review and let me know what you mean by this? Also, you'll need to add the new page to the SUMMARY.md page (I always forget too!).
Thanks!

**Comment by anastasiaUsik** [comment]
@YVLopez it was about this bug
 [MPD-1873](https://meecosystem.atlassian.net/browse/MPD-1873)
[Sandbox] After establishing connection with already connected organisation the message shows me "Success"
Can you help me please with rewriting this sentence?

[MPD-1873]: https://meecosystem.atlassian.net/browse/MPD-1873?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

**Review by javereec — APPROVED** [review]
Great work @anastasiaUsik. Thanks for reviewing @YVLopez

**Comment by YVLopez** [comment]
@anastasiaUsik, that makes sense. In that case, I would change it to:
"Fixed the toast message that appears when trying to connect to an existing Organisation."

**Pull request merged**
